namespace CSMaterial.DeferWindowsPos;

public enum WindowPosFlags : uint
{
	SWP_DRAWFRAME = 32u,
	SWP_FRAMECHANGED = 32u,
	SWP_HIDEWINDOW = 128u,
	SWP_NOACTIVATE = 16u,
	SWP_NOCOPYBITS = 256u,
	SWP_NOMOVE = 2u,
	SWP_NOOWNERZORDER = 512u,
	SWP_NOREDRAW = 8u,
	SWP_NOREPOSITION = 512u,
	SWP_NOSENDCHANGING = 1024u,
	SWP_NOSIZE = 1u,
	SWP_NOZORDER = 4u,
	SWP_SHOWWINDOW = 64u
}
